name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Store GPG private key in a file
        run: |
          echo ${{ secrets.GPG_PRIVATE_KEY }} | base64 --decode > /tmp/GPG_PRIVATE_KEY.gpg

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          distribution: goreleaser
          version: 'v2.3.2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
          GPG_PRIVATE_KEY_PATH: /tmp/GPG_PRIVATE_KEY.gpg
          NFPM_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Remove GPG private key file
        if: always()
        run: |
          rm -rf /tmp/GPG_PRIVATE_KEY.asc
